package ninja.javahacker.jaspasema;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Year;
import java.time.YearMonth;
import lombok.NonNull;
import ninja.javahacker.jaspasema.exceptions.badmapping.BadServiceMappingException;
import ninja.javahacker.jaspasema.exceptions.badmapping.ImplicitWithJsVarException;
import ninja.javahacker.jaspasema.ext.ObjectUtils;
import ninja.javahacker.jaspasema.format.ParameterParser;
import ninja.javahacker.jaspasema.processor.AnnotatedParameter;
import ninja.javahacker.jaspasema.processor.ParamProcessor;
import ninja.javahacker.jaspasema.processor.ParamSource;

/**
 * Denotes that the value of a method parameter should be read from a request header.
 *
 * <p>For example:</p>
 * <pre>
 *     &#64;Get
 *     &#64;Path("/foo")
 *     public String foo(
 *         &#64;HeaderParam String bar,                                     // Uses the content of the "bar" header.
 *         &#64;HeaderParam(name = "user-agent") String userAgent,          // Uses the content of the "user-agent" header.
 *         &#64;HeaderParam(dateFormat = "dd/MM/uuuu") LocalDate loginDate) // Sets a date format for the header.
 *     {
 *         // Do stuff.
 *     }
 * </pre>
 * @author Victor Williams Stafusa da Silva
 */
@ParamSource(processor = HeaderParam.Processor.class)
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
public @interface HeaderParam {

    /**
     * This tells which is the desired date format for converting the value of the header to an instance of {@link LocalDate}
     * {@link LocalDateTime}, {@link LocalTime}, {@link Year} or {@link YearMonth}.
     * <p>Example of valid formats includes {@code "dd-MM-uuuu"}, {@code "dd/MM/uuuu HH:mm:ss"}, {@code "MM/uuuu"} among others.</p>
     * <p>This field is mandatory if the parameter type is one of the aforemetioned formats. Otherwise, this field should not be used.</p>
     * @see <a href="https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/time/format/DateTimeFormatter.html#patterns">Patterns</a>
     * @return The desired date format.
     */
    public String dateFormat() default "";

    /**
     * The name of the header. Uses the name of the parameter if blank or left unspecified.
     * @return The name of the header.
     */
    public String name() default "";

    /**
     * Defines the name of the variable used to hold the value of this parameter in the autogenerated javascript stub.
     * If unspecified, this defaults to the parameter name.
     * <p>This should be left as blank/unspecified if the {@link #implicit()} field is set to {@code true}.</p>
     * @return The name of the variable used to hold the value of this parameter in the autogenerated javascript stub.
     */
    public String jsVar() default "";

    /**
     * Defines whether the javascript code for populating this header should or should not be genenerated in autogenerated
     * javascript client stubs. Defaults to {@code false}.
     * <p>If this is set to {@code true} the field {@link #jsVar()} should be left as blank/unspecified.</p>
     * @return Whether the javascript code for populating this header should or should not be genenerated in autogenerated
     *         javascript client stubs.
     */
    public boolean implicit() default false;

    /**
     * The class that is responsible for processing the {@link HeaderParam} annotation.
     * @author Victor Williams Stafusa da Silva
     */
    public static class Processor implements ParamProcessor<HeaderParam> {

        private static final String TEMPLATE = "__customHeaders.push({name: '#N#', value: #JS#});";

        /**
         * Sole constructor.
         */
        public Processor() {
        }

        /**
         * {@inheritDoc}
         * @param <E> {@inheritDoc}
         * @param param {@inheritDoc}
         * @return {@inheritDoc}
         * @throws BadServiceMappingException {@inheritDoc}
         */
        @NonNull
        @Override
        public <E> Stub<E> prepare(@NonNull AnnotatedParameter<HeaderParam, E> param) throws BadServiceMappingException {
            var annotation = param.getAnnotation();
            var paramName = param.getParameterName();
            if (annotation.implicit() && !annotation.jsVar().isEmpty()) throw new ImplicitWithJsVarException(param);
            var choosenName = ObjectUtils.choose(annotation.name(), paramName);
            var js = ObjectUtils.choose(annotation.jsVar(), paramName);
            var part = ParameterParser.prepare(param, annotation.dateFormat());
            var t1 = annotation.implicit() ? "" : js;
            var t2 = annotation.implicit() ? "" : TEMPLATE.replace("#N#", choosenName).replace("#JS#", js);
            return new Stub<>(ctx -> part.make(ctx.header(choosenName)), t1, t2);
        }
    }
}