package ninja.javahacker.jaspasema;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import lombok.NonNull;
import ninja.javahacker.jaspasema.exceptions.badmapping.BadServiceMappingException;
import ninja.javahacker.jaspasema.exceptions.badmapping.ImplicitWithJsVarException;
import ninja.javahacker.jaspasema.exceptions.paramvalue.MalformedParameterValueException;
import ninja.javahacker.jaspasema.ext.ObjectUtils;
import ninja.javahacker.jaspasema.processor.AnnotatedParameter;
import ninja.javahacker.jaspasema.processor.JsonTypesProcessor;
import ninja.javahacker.jaspasema.processor.ParamProcessor;
import ninja.javahacker.jaspasema.processor.ParamSource;

/**
 * Denotes that the value of a method parameter should be read from a request header as
 * a JSON and the value deserialized as an object from that JSON.
 *
 * <p>For example:</p>
 * <pre>
 *     &#64;Get
 *     &#64;Path("/foo")
 *     public String foo(
 *         // Uses the content of the "f1" header, reads it as a JSON and deserializes a Fruit instance.
 *         &#64;HeaderJsonParam Fruit f1,
 *         // Uses the content of the "X-flavor" header, reads it as a JSON and deserializes a Flavor instance.
 *         &#64;HeaderJsonParam(name = "X-flavor") Flavor f2)
 *     {
 *         // Do stuff.
 *     }
 * </pre>
 * @author Victor Williams Stafusa da Silva
 */
@ParamSource(processor = HeaderJsonParam.Processor.class)
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
public @interface HeaderJsonParam {

    /**
     * Defines if the JSON should be read in lenient mode or not.
     * In lenient mode, unknown properties in the JSON are simply ignored. In strict mode, their presence triggers an error.
     * <p>The default value is {@code false}. I.e. to NOT be lenient.</p>
     * @return If the JSON should be read in lenient mode or not.
     */
    public boolean lenient() default false;

    /**
     * The name of the header. Uses the name of the parameter if blank or left unspecified.
     * @return The name of the header.
     */
    public String name() default "";

    /**
     * Defines the name of the variable used to hold the value of this parameter in the autogenerated javascript stub.
     * If unspecified, this defaults to the parameter name.
     * <p>This should be left as blank/unspecified if the {@link #implicit()} field is set to {@code true}.</p>
     * @return The name of the variable used to hold the value of this parameter in the autogenerated javascript stub.
     */
    public String jsVar() default "";

    /**
     * Defines whether the javascript code for populating this header should or should not be genenerated in autogenerated
     * javascript client stubs. Defaults to {@code false}.
     * <p>If this is set to {@code true} the field {@link #jsVar()} should be left as blank/unspecified.</p>
     * @return Whether the javascript code for populating this header should or should not be genenerated in autogenerated
     *         javascript client stubs.
     */
    public boolean implicit() default false;

    /**
     * The class that is responsible for processing the {@link HeaderJsonParam} annotation.
     * @author Victor Williams Stafusa da Silva
     */
    public static final class Processor implements ParamProcessor<HeaderJsonParam> {

        private static final String TEMPLATE = "__customHeaders.push({name: '#N#', value: #JS#});";

        /**
         * Sole constructor.
         */
        public Processor() {
        }

        /**
         * {@inheritDoc}
         * @param <E> {@inheritDoc}
         * @param param {@inheritDoc}
         * @return {@inheritDoc}
         * @throws BadServiceMappingException {@inheritDoc}
         */
        @NonNull
        @Override
        public <E> Stub<E> prepare(@NonNull AnnotatedParameter<HeaderJsonParam, E> param) throws BadServiceMappingException {
            var annotation = param.getAnnotation();
            var jsVar = annotation.jsVar();
            var paramName = param.getParameterName();
            if (annotation.implicit() && !jsVar.isEmpty()) throw new ImplicitWithJsVarException(param);
            var choosenName = ObjectUtils.choose(annotation.name(), paramName);
            var js = ObjectUtils.choose(jsVar, paramName);
            var t1 = annotation.implicit() ? "" : js;
            var t2 = annotation.implicit() ? "" : TEMPLATE.replace("#N#", choosenName).replace("#JS#", js);
            ParamProcessor.Worker<E> w = ctx -> {
                var s = ctx.header(choosenName);
                var c = MalformedParameterValueException.expectingCause(param, s);
                return JsonTypesProcessor.readJson(annotation.lenient(), param.getTarget(), s, c);
            };
            return new Stub<>(w, t1, t2);
        }
    }
}